version: '3.5'

services:
  db_auth:
    container_name: db_auth
    image: postgres:15
    environment:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=root
          - PGDATA=/data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - '5432:5432'
    restart: always
    networks:
      - arch-network
  arch:
    tty: true
    container_name: arch
    volumes:
      - .:/opt/arch
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - arch-network

volumes:
  db:

networks:
  arch-network:
    driver: "bridge"
    external: false